name: Check links

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'

      # Using asciidoc-link-check to check asciidoc docs
      - name: Install asciidoc-link-check
        run: |
          npm i asciidoc-link-check

      - name: Check adoc files
        run: |
          find . \
            -name docs -prune -o \
            -name node_modules -prune -o \
            -name vendor -prune -o \
            -iname '*.md' \
            -exec ./node_modules/asciidoc-link-check/asciidoc-link-check --config .github/workflows/link-check-config.json {} +
